---

- name: Install updates
  hosts: all
  become: true
  pre_tasks:

    - name: Install updates (RedHat)
      tags: always
      ansible.builtin.dnf:
        update_only: true
        update_cache: true
      when: ansible_distribution == "RedHat"

    - name: Install updated (Ubuntu)
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Configure web services
  hosts: web_servers
  become: true
  tasks:

    - name: Install apache and php (Ubuntu)
      tags: apache,apache2,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install apache and php (RedHat)
      tags: apache,httpd,redhat
      ansible.builtin.dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "RedHat"

- name: Configure db servers
  hosts: db_servers
  become: true
  tasks:

    - name: Install mariadb package (RedHat)
      tags: mariadb,redhat
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Install mariadb package (Ubuntu)
      tags: mariadb,ubuntu
      ansible.builtin.apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- name: Configure file servers
  hosts: file_servers
  become: true
  tasks:

    - name: Install samba package
      tags: samba
      ansible.builtin.package:
        name: samba
        state: latest
