---

- name: Install updates
  hosts: all
  become: true
  pre_tasks:

    - name: Update repository index (RedHat)
      tags: always
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "RedHat"
  
    - name: Update repository index (Ubuntu)
      tags: always
      ansible.builtin.apt:
        update_cache: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- name: Base
  hosts: all
  become: true
  roles:
    - base

- name: Configure web services
  hosts: web_servers
  become: true
  roles:
    - web_servers
- name: Configure db servers
  hosts: db_servers
  become: true
  roles:
    - db_servers

- name: Configure file servers
  hosts: file_servers
  become: true
  roles:
    - file_servers

- name: Configure workstations
  hosts: workstations
  become: true
  roles:
    - workstations
