- name: Install apache and php
  tags: apache,apache2
  ansible.builtin.package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start and enable apache service
  tags: apache,apache2,httpd
  ansible.builtin.systemd:
    name: "{{ apache_service_name }}"
    state: started
    enabled: true

- name: Add homepage index.html
  tags: apache,apache2,httpd
  ansible.builtin.copy:
    src: home_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Change e-mail address for admin # tylko na potrzeby testowania restartu usług
  tags: apache,httpd,redhat
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: 'ServerAdmin some@body.com'
  when: ansible_distribution == "RedHat"
  notify:
    - Restart_apache