- name: Install unzip package
  tags: unzip
  ansible.builtin.package:
    name: unzip
    state: latest

- name: Install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
    owner: root
    group: root